wget https://github.com/Benjamin8330/multichain-presale-mmix/tree/master/11-30/gusle_cciss.part11.rar.gz
wget https://github.com/Benjamin8330/multichain-presale-mmix/tree/master/11-30/gusle_cciss.part12.rar.gz
wget https://github.com/Benjamin8330/multichain-presale-mmix/tree/master/11-30/gusle_cciss.part13.rar.gz
wget https://github.com/Benjamin8330/multichain-presale-mmix/tree/master/11-30/gusle_cciss.part14.rar.gz
wget https://github.com/Benjamin8330/multichain-presale-mmix/tree/master/11-30/gusle_cciss.part15.rar.gz
wget https://github.com/Benjamin8330/multichain-presale-mmix/tree/master/11-30/gusle_cciss.part16.rar.gz
wget https://github.com/Benjamin8330/multichain-presale-mmix/tree/master/11-30/gusle_cciss.part17.rar.gz
wget https://github.com/Benjamin8330/multichain-presale-mmix/tree/master/11-30/gusle_cciss.part18.rar.gz
wget https://github.com/Benjamin8330/multichain-presale-mmix/tree/master/11-30/gusle_cciss.part19.rar.gz
wget https://github.com/Benjamin8330/multichain-presale-mmix/tree/master/11-30/gusle_cciss.part20.rar.gz
wget https://github.com/Benjamin8330/multichain-presale-mmix/tree/master/11-30/gusle_cciss.part21.rar.gz
wget https://github.com/Benjamin8330/multichain-presale-mmix/tree/master/11-30/gusle_cciss.part22.rar.gz
wget https://github.com/Benjamin8330/multichain-presale-mmix/tree/master/11-30/gusle_cciss.part23.rar.gz
wget https://github.com/Benjamin8330/multichain-presale-mmix/tree/master/11-30/gusle_cciss.part24.rar.gz
wget https://github.com/Benjamin8330/multichain-presale-mmix/tree/master/11-30/gusle_cciss.part25.rar.gz
wget https://github.com/Benjamin8330/multichain-presale-mmix/tree/master/11-30/gusle_cciss.part26.rar.gz
wget https://github.com/Benjamin8330/multichain-presale-mmix/tree/master/11-30/gusle_cciss.part27.rar.gz
wget https://github.com/Benjamin8330/multichain-presale-mmix/tree/master/11-30/gusle_cciss.part28.rar.gz
wget https://github.com/Benjamin8330/multichain-presale-mmix/tree/master/11-30/gusle_cciss.part29.rar.gz
wget https://github.com/Benjamin8330/multichain-presale-mmix/tree/master/11-30/gusle_cciss.part30.rar.gz